package com.finalboss.runelite.model;

import lombok.Data;
import java.util.Date;

/**
 * Data model representing a player's activity status.
 *
 * Maps to the 'statuses' table in Supabase:
 * - id: UUID primary key (auto-generated)
 * - rsn: Player's RuneScape name (unique constraint)
 * - status: Activity status (e.g., "Available", "TOB", "Bossing")
 * - note: Optional note/details about the activity
 * - updated_at: Timestamp when status was last updated
 * - expires_at: Timestamp when status should expire (null = never)
 *
 * Field naming uses snake_case to match Supabase/PostgreSQL conventions
 * for direct Gson serialization/deserialization.
 *
 * @see ApiClient#getStatuses() for fetching status records
 * @see ApiClient#setStatus(String, String, int) for creating/updating status
 */
@Data
public class StatusRecord
{
    /** UUID primary key (auto-generated by Supabase) */
    private String id;

    /** Player's RuneScape name (unique) */
    private String rsn;

    /** Activity status: Available, Bossing, TOB, COX, TOA, Skilling, AFK, Do Not Disturb */
    private String status;

    /** Optional note/details about the activity */
    private String note;

    /** Timestamp when status was last updated */
    private Date updated_at;

    /** Timestamp when status expires (null = never expires) */
    private Date expires_at;

    /**
     * Check if this status has expired.
     * Expired statuses should be filtered out when displaying the roster.
     *
     * @return true if expires_at is set and in the past, false otherwise
     */
    public boolean isExpired()
    {
        if (expires_at == null)
        {
            return false;  // No expiration set - status persists indefinitely
        }
        return new Date().after(expires_at);
    }
}
